const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Starting MonadPay Smart Contract Deployment...\n");

  const [deployer] = await hre.ethers.getSigners();
  console.log("📝 Deploying contracts with account:", deployer.address);
  
  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("💰 Account balance:", hre.ethers.formatEther(balance), "MON\n");

  if (balance === 0n) {
    throw new Error("❌ Insufficient balance. Please fund your deployer account.");
  }

  const deploymentInfo = {
    network: hre.network.name,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {},
  };

  try {
    // Step 1: Deploy HandleRegistry
    console.log("📦 Step 1: Deploying HandleRegistry...");
    const HandleRegistry = await hre.ethers.getContractFactory("HandleRegistry");
    const handleRegistry = await HandleRegistry.deploy();
    await handleRegistry.waitForDeployment();
    const handleRegistryAddress = await handleRegistry.getAddress();
    
    console.log("✅ HandleRegistry deployed to:", handleRegistryAddress);
    deploymentInfo.contracts.HandleRegistry = {
      address: handleRegistryAddress,
      txHash: handleRegistry.deploymentTransaction()?.hash,
    };

    // Verify deployment
    const handleFee = await handleRegistry.HANDLE_FEE();
    console.log("   Handle Fee:", hre.ethers.formatEther(handleFee), "MON\n");

    // Step 2: Deploy Payment Contract
    console.log("📦 Step 2: Deploying Payment contract...");
    const Payment = await hre.ethers.getContractFactory("Payment");
    const payment = await Payment.deploy(handleRegistryAddress);
    await payment.waitForDeployment();
    const paymentAddress = await payment.getAddress();
    
    console.log("✅ Payment deployed to:", paymentAddress);
    deploymentInfo.contracts.Payment = {
      address: paymentAddress,
      txHash: payment.deploymentTransaction()?.hash,
    };

    // Verify deployment
    const registryAddress = await payment.handleRegistry();
    console.log("   Connected to HandleRegistry:", registryAddress, "\n");

    // Step 3: Deploy PaymentRequest Contract
    console.log("📦 Step 3: Deploying PaymentRequest contract...");
    const PaymentRequest = await hre.ethers.getContractFactory("PaymentRequest");
    const paymentRequest = await PaymentRequest.deploy(handleRegistryAddress);
    await paymentRequest.waitForDeployment();
    const paymentRequestAddress = await paymentRequest.getAddress();
    
    console.log("✅ PaymentRequest deployed to:", paymentRequestAddress);
    deploymentInfo.contracts.PaymentRequest = {
      address: paymentRequestAddress,
      txHash: paymentRequest.deploymentTransaction()?.hash,
    };

    // Verify deployment
    const requestRegistryAddress = await paymentRequest.handleRegistry();
    console.log("   Connected to HandleRegistry:", requestRegistryAddress, "\n");

    // Save deployment info
    const deploymentDir = path.join(__dirname, "..", "deployments");
    if (!fs.existsSync(deploymentDir)) {
      fs.mkdirSync(deploymentDir, { recursive: true });
    }

    const deploymentFile = path.join(
      deploymentDir,
      `deployment-${hre.network.name}-${Date.now()}.json`
    );
    fs.writeFileSync(deploymentFile, JSON.stringify(deploymentInfo, null, 2));
    console.log("💾 Deployment info saved to:", deploymentFile);

    // Create/update .env file for middleware
    const envFile = path.join(__dirname, "..", "..", "middleware", ".env");
    const envContent = `# MonadPay Middleware Configuration
# Generated by deployment script on ${new Date().toISOString()}

# Monad Blockchain RPC URL
MONAD_RPC_URL=${process.env.MONAD_RPC_URL || "http://localhost:8545"}

# Smart Contract Addresses
HANDLE_REGISTRY_ADDRESS=${handleRegistryAddress}
PAYMENT_CONTRACT_ADDRESS=${paymentAddress}
PAYMENT_REQUEST_CONTRACT_ADDRESS=${paymentRequestAddress}

# Server Configuration
PORT=3001
NODE_ENV=production
`;

    fs.writeFileSync(envFile, envContent);
    console.log("📝 Middleware .env file updated:", envFile);

    // Summary
    console.log("\n" + "=".repeat(60));
    console.log("✅ DEPLOYMENT COMPLETE!");
    console.log("=".repeat(60));
    console.log("\n📋 Contract Addresses:");
    console.log("   HandleRegistry:    ", handleRegistryAddress);
    console.log("   Payment:            ", paymentAddress);
    console.log("   PaymentRequest:     ", paymentRequestAddress);
    console.log("\n📝 Next Steps:");
    console.log("   1. Verify contracts on block explorer (if available)");
    console.log("   2. Update middleware .env with contract addresses");
    console.log("   3. Start middleware: cd middleware && npm run dev");
    console.log("   4. Test contract interactions\n");

  } catch (error) {
    console.error("\n❌ Deployment failed:", error);
    process.exit(1);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });



